apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-api-config
  namespace: infra-advisor
data:
  LOG_LEVEL: "INFO"
  DD_SERVICE: "infraadvisor-auth-api"
  DD_ENV: "dev"
  DD_VERSION: "latest"
  DD_AGENT_HOST: "datadog-agent.datadog.svc.cluster.local"
  DD_TRACE_AGENT_PORT: "8126"
  DD_LOGS_INJECTION: "true"
  DD_CODE_ORIGIN_FOR_SPANS_ENABLED: "true"
  DD_DBM_PROPAGATION_MODE: "full"
  SMTP_HOST: "mailhog.infra-advisor.svc.cluster.local"
  SMTP_PORT: "1025"
  SMTP_FROM: "infra-advisor-ai@demo.local"
  SMTP_TLS: "false"
  APP_BASE_URL: "https://infra-advisor-ai.kyletaylor.dev"
