import ddtrace.auto  # must be first import — enables APM auto-instrumentation

"""
generate_synthetic_docs.py
==========================

Generates exactly 80 synthetic knowledge base documents and upserts them into
Azure AI Search.  Generation is idempotent: if the index already contains
≥ 80 documents with source='synthetic', the script exits immediately without
calling the LLM.

Document inventory (80 total):
  - 20 project close-out reports  (transportation 8, water 8, energy 4)
  - 12 proposal templates          (all domains; 4 water-specific)
  - 10 cost estimation guides      (bridge rehab 3, water treatment 3, pipeline 2, grid resilience 2)
  -  8 engineering standards summaries
  -  8 risk assessment frameworks
  -  6 client briefing templates
  - 10 water-specific market intelligence docs
  -  6 funding and grants guides

Each document:
  - Generated by GPT-4o with a structured, domain-realistic prompt
  - 500–2,000 words
  - References real standards (AASHTO LRFD, ASCE 7, EPA SDWA, TWDB SWIFT, AWWA, TCEQ)
  - Chunked at 512 tokens with 64-token overlap using tiktoken (cl100k_base)
  - Embedded via text-embedding-ada-002
  - Upserted into Azure AI Search

Chunk ID format: synthetic_{document_slug}_{chunk_index}  (deterministic)
"""

import logging
import os
import re
import sys
from datetime import datetime, timezone
from typing import Any

import tiktoken
from azure.core.credentials import AzureKeyCredential
from azure.search.documents import SearchClient
from openai import AzureOpenAI

log = logging.getLogger(__name__)
logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------
SYNTHETIC_SOURCE = "synthetic"
MIN_SYNTHETIC_DOCS = 80
CHUNK_SIZE_TOKENS = 512
CHUNK_OVERLAP_TOKENS = 64
EMBEDDING_MODEL = "text-embedding-ada-002"
COMPLETION_MODEL = "gpt-4o"

# ---------------------------------------------------------------------------
# Document specifications (80 documents)
# ---------------------------------------------------------------------------
DOCUMENT_SPECS: list[dict[str, Any]] = [
    # =========================================================================
    # PROJECT CLOSE-OUT REPORTS — Transportation (8)
    # =========================================================================
    {
        "slug": "closeout_bridge_rehab_brazoria_county",
        "title": "Project Close-Out Report: Brazoria County CR-48 Bridge Rehabilitation",
        "domain": "transportation",
        "document_type": "project_closeout_report",
        "prompt": (
            "Write a 600–900 word project close-out report for a bridge rehabilitation project on a "
            "county road bridge in Brazoria County, Texas. The bridge was built in 1962, had a "
            "sufficiency rating of 42.3, and was structurally deficient. The project involved deck "
            "replacement, substructure repair, scour countermeasures, and load rating upgrade to "
            "HL-93. Reference AASHTO LRFD 9th Edition, TXDOT Bridge Design Manual, and TxDOT "
            "standard specifications. Include actual construction cost ($3.2M), schedule performance, "
            "lessons learned about scour inspection during low-water access, and post-construction "
            "inspection findings. Use professional engineering report format."
        ),
    },
    {
        "slug": "closeout_bridge_widening_harris_county",
        "title": "Project Close-Out Report: Harris County IH-10 Overpass Widening",
        "domain": "transportation",
        "document_type": "project_closeout_report",
        "prompt": (
            "Write a 700–1000 word project close-out report for a highway overpass widening project "
            "on the IH-10 corridor in Harris County, Texas. The project added a 12-foot outside lane "
            "and ADA-compliant sidewalk on a three-span concrete box girder bridge carrying 85,000 ADT. "
            "Reference AASHTO LRFD, FHWA load rating guidelines, and Harris County Toll Road "
            "Authority design standards. Include post-widening load rating results, construction "
            "sequencing for maintained traffic, and lessons learned about falsework permits in FEMA "
            "flood zones. Budget: $8.7M, completed 11 days ahead of schedule."
        ),
    },
    {
        "slug": "closeout_bridge_scour_repair_bexar",
        "title": "Project Close-Out Report: Bexar County Scour Critical Bridge Emergency Repair",
        "domain": "transportation",
        "document_type": "project_closeout_report",
        "prompt": (
            "Write a 600–800 word close-out report for an emergency scour repair project on a "
            "1974-era concrete bridge in Bexar County flagged as scour critical after the 2021 "
            "flood event. Scope included pier underpinning with micropiles, riprap installation, "
            "and monitoring well installation. Reference FHWA HEC-18 Scour at Bridges, AASHTO "
            "LRFD, and FEMA BRIC grant requirements. Include geotechnical findings, contractor "
            "performance notes, and the post-repair National Bridge Inspection Standard (NBIS) "
            "rating improvement from 3 to 6 on substructure condition. Emergency contract value: $1.4M."
        ),
    },
    {
        "slug": "closeout_bridge_inspection_statewide",
        "title": "Project Close-Out Report: Statewide Bridge Inspection Program — Cycle 12",
        "domain": "transportation",
        "document_type": "project_closeout_report",
        "prompt": (
            "Write a 700–900 word close-out report for a statewide bridge inspection program "
            "covering 412 structures across 22 Texas counties under NBIS 24-month cycle requirements. "
            "Reference FHWA Bridge Inspector's Reference Manual, AASHTO Manual for Bridge Evaluation, "
            "and TxDOT Bridge Inspection Manual. Include quality control findings, structures flagged "
            "for follow-up engineering, average condition rating improvements, and recommendations for "
            "the next inspection cycle. Discuss underwater inspection findings at 14 scour-critical sites "
            "on the Brazos River corridor. Contract value: $2.1M."
        ),
    },
    {
        "slug": "closeout_highway_pavement_rehab_dallas",
        "title": "Project Close-Out Report: Dallas District US-75 Pavement Rehabilitation",
        "domain": "transportation",
        "document_type": "project_closeout_report",
        "prompt": (
            "Write a 600–800 word project close-out report for a 14-mile pavement rehabilitation "
            "project on US-75 in the Dallas TxDOT district. Scope included mill-and-overlay with "
            "perpetual pavement design, ADA ramp upgrades at 38 intersections, and drainage improvements. "
            "Reference AASHTO Pavement Design Guide, TxDOT Pavement Design Manual, and FHWA Every Day "
            "Counts initiatives. Include IRI before/after data, construction quality testing results, "
            "and public communication lessons learned. Contract: $19.2M, 24-month construction period."
        ),
    },
    {
        "slug": "closeout_bridge_load_rating_nueces",
        "title": "Project Close-Out Report: Nueces County Coastal Bridge Load Rating and Fatigue Assessment",
        "domain": "transportation",
        "document_type": "project_closeout_report",
        "prompt": (
            "Write a 700–900 word close-out report for a load rating and fatigue assessment project "
            "covering 28 coastal bridges in Nueces County, Texas. Focus on steel girder fatigue "
            "category evaluation, hurricane wind load analysis per ASCE 7, and marine environment "
            "coating assessment. Reference AASHTO Manual for Bridge Evaluation, FHWA Fatigue and "
            "Fracture guidelines, and Texas coastal design criteria. Include load rating summary table, "
            "fatigue life remaining estimates, and recommended painting/maintenance intervals. "
            "Contract: $780K."
        ),
    },
    {
        "slug": "closeout_traffic_signal_modernization_travis",
        "title": "Project Close-Out Report: Travis County Traffic Signal Modernization",
        "domain": "transportation",
        "document_type": "project_closeout_report",
        "prompt": (
            "Write a 600–800 word close-out report for a traffic signal modernization project "
            "upgrading 84 signalized intersections in Travis County to adaptive signal control "
            "technology (ASCT). Reference MUTCD, TxDOT Traffic Signal Design Manual, and FHWA "
            "Every Day Counts ATMS guidelines. Include intersection performance data (before/after "
            "vehicle delay, fuel consumption), procurement lessons learned for connected vehicle "
            "infrastructure, and ADA pedestrian signal compliance outcomes. Contract: $6.4M."
        ),
    },
    {
        "slug": "closeout_interstate_drainage_galveston",
        "title": "Project Close-Out Report: Galveston County IH-45 Drainage and Resiliency Improvements",
        "domain": "transportation",
        "document_type": "project_closeout_report",
        "prompt": (
            "Write a 700–1000 word close-out report for a drainage resiliency project on IH-45 in "
            "Galveston County following Hurricane Harvey. Scope included culvert upsizing, outfall "
            "channel stabilization, FEMA 100-year floodplain encroachment mitigation, and pavement "
            "repair. Reference ASCE 7, FEMA hazard mitigation grant program (HMGP) requirements, "
            "TXDOT hydraulic design manual, and Gulf Coast regional storm surge modeling. Include "
            "post-construction 2-year storm performance data, FEMA HMGP closeout documentation "
            "requirements, and contractor lessons learned. HMGP grant: $4.1M; local match: $1.0M."
        ),
    },

    # =========================================================================
    # PROJECT CLOSE-OUT REPORTS — Water (8)
    # =========================================================================
    {
        "slug": "closeout_water_treatment_corpus_christi",
        "title": "Project Close-Out Report: Corpus Christi O.N. Stevens Water Treatment Plant Expansion",
        "domain": "water",
        "document_type": "project_closeout_report",
        "prompt": (
            "Write an 800–1100 word project close-out report for a 30 MGD capacity expansion of the "
            "O.N. Stevens Water Treatment Plant in Corpus Christi, Texas. Scope included sedimentation "
            "basin expansion, ozone disinfection system addition, membrane filtration for brackish "
            "blending, SCADA upgrade, and TCEQ permit modification. Reference AWWA design standards, "
            "EPA Surface Water Treatment Rule (SWTR), TCEQ Chapter 290 drinking water regulations, "
            "and TWDB SWIFT loan program compliance requirements. Include treatment performance data, "
            "energy efficiency outcomes, and lessons learned about construction in a live plant environment. "
            "Contract: $47.3M. TWDB SWIFT financing: $38M."
        ),
    },
    {
        "slug": "closeout_desalination_feasibility_coastal",
        "title": "Project Close-Out Report: South Texas Coastal Desalination Feasibility Study",
        "domain": "water",
        "document_type": "project_closeout_report",
        "prompt": (
            "Write a 700–900 word close-out report for a desalination feasibility study for a "
            "coastal Texas municipality in Region N (South Texas) facing freshwater supply shortages. "
            "The study evaluated seawater reverse osmosis (SWRO) at two intake configurations, "
            "brackish groundwater RO as an alternative, and a hybrid surface water/RO option. "
            "Reference TWDB 2026 State Water Plan (Region N water supply deficits), AWWA "
            "desalination best practices, Texas water rights law Chapter 11 Water Code, and EPA "
            "concentrate management guidelines. Include capital cost estimates, energy cost modeling, "
            "TCEQ permitting timeline, and recommendation for a pilot test program. Study cost: $890K."
        ),
    },
    {
        "slug": "closeout_wastewater_reuse_san_antonio",
        "title": "Project Close-Out Report: San Antonio Water System Indirect Potable Reuse Expansion",
        "domain": "water",
        "document_type": "project_closeout_report",
        "prompt": (
            "Write an 800–1000 word close-out report for a potable water reuse project expanding "
            "the Dos Rios Water Recycling Center effluent to Edwards Aquifer recharge. Reference "
            "TCEQ Chapter 210 Water Reuse regulations, EPA Guidelines for Water Reuse, AWWA water "
            "reuse standards, and TWDB 2026 Water Plan Region J (Plateau) strategies. Include "
            "advanced treatment train design (MF/RO/UV-AOP), aquifer recharge permitting outcomes, "
            "groundwater monitoring well results, public engagement outcomes, and O&M cost per "
            "acre-foot compared to fresh surface water. Contract: $62M. CWSRF financing."
        ),
    },
    {
        "slug": "closeout_rural_water_compliance_panhandle",
        "title": "Project Close-Out Report: Panhandle Rural Water District TCR Compliance Improvements",
        "domain": "water",
        "document_type": "project_closeout_report",
        "prompt": (
            "Write a 600–800 word close-out report for a compliance improvement project for a small "
            "rural water supply corporation in the Texas Panhandle (TWDB planning Region A/B) with "
            "recurring Total Coliform Rule (TCR) violations and pressure zone deficiencies. Scope "
            "included 12 miles of main replacement, booster pump station, emergency interconnect "
            "with a neighboring district, and SCADA installation. Reference TCEQ Chapter 290, "
            "EPA TCR/RTCR regulations, AWWA distribution system guidelines, and TWDB Economically "
            "Distressed Areas Program (EDAP) funding requirements. Include compliance timeline, "
            "post-project violation status, and operator training outcomes. EDAP grant: $2.4M."
        ),
    },
    {
        "slug": "closeout_aquifer_storage_recovery_hill_country",
        "title": "Project Close-Out Report: Texas Hill Country ASR Feasibility and Pilot",
        "domain": "water",
        "document_type": "project_closeout_report",
        "prompt": (
            "Write a 700–900 word close-out report for an Aquifer Storage and Recovery (ASR) "
            "feasibility and pilot project in the Texas Hill Country (Region J/K). The project "
            "included hydrogeological characterization of the Trinity Aquifer, pilot injection and "
            "recovery testing, water quality modeling for mixing zones, and TCEQ Class V injection "
            "well permitting. Reference TWDB ASR guidance, Texas Water Code Chapter 27 (injection "
            "wells), TCEQ UIC program, and AWWA ASR best practices. Include recovery efficiency "
            "metrics, aquifer response data, estimated full-scale cost per acre-foot, and regulatory "
            "pathway assessment. Study and pilot cost: $1.8M."
        ),
    },
    {
        "slug": "closeout_flood_control_rio_grande_valley",
        "title": "Project Close-Out Report: Rio Grande Valley Drainage Improvement Program",
        "domain": "water",
        "document_type": "project_closeout_report",
        "prompt": (
            "Write an 800–1000 word close-out report for a regional drainage improvement program "
            "in the Rio Grande Valley (Hidalgo and Cameron Counties, TWDB Region M). Scope included "
            "14 miles of drainage channel improvements, 3 detention ponds, pump station upgrades, "
            "and FEMA floodplain remapping. Reference FEMA NFIP requirements, ASCE 7 flood load "
            "criteria, TWDB 2026 water plan flood mitigation strategies for Region M, and EPA "
            "Clean Water Act Section 404 wetland permitting. Include hydraulic modeling results, "
            "post-construction flood level reduction estimates, FEMA LOMR submittal outcomes, and "
            "FEMA BRIC grant compliance. Contract: $28.6M."
        ),
    },
    {
        "slug": "closeout_groundwater_conservation_district_wells",
        "title": "Project Close-Out Report: Carrizo-Wilcox Aquifer Well Field Assessment",
        "domain": "water",
        "document_type": "project_closeout_report",
        "prompt": (
            "Write a 700–900 word close-out report for an aquifer assessment and well field "
            "expansion study for a regional water authority drawing from the Carrizo-Wilcox Aquifer "
            "in East Texas (TWDB Region D). Included aquifer test program (15 production wells), "
            "groundwater availability model calibration, managed aquifer depletion analysis, and "
            "Groundwater Conservation District permit strategy. Reference TWDB groundwater "
            "management area rules, Texas Water Code Chapter 36, AWWA groundwater supply guidelines, "
            "and TWDB Groundwater Availability Modeling program. Include sustainable yield "
            "estimates by decade through 2080 and recommended well spacing. Study: $640K."
        ),
    },
    {
        "slug": "closeout_water_asset_management_houston",
        "title": "Project Close-Out Report: Houston Water Asset Management Plan Development",
        "domain": "water",
        "document_type": "project_closeout_report",
        "prompt": (
            "Write an 800–1100 word close-out report for development of a 20-year Capital Improvement "
            "Plan and Asset Management Plan for a mid-size Texas municipal water utility. The project "
            "inventoried 340 miles of water mains, 18 pump stations, and 4 water storage facilities; "
            "assessed condition using CCTV inspection data and break history analysis; and developed "
            "risk-based renewal prioritization. Reference AWWA Asset Management framework, GASB 34 "
            "reporting requirements, EPA SDWA infrastructure needs assessment, TCEQ Chapter 290 "
            "operations requirements, and TWDB SWIFT loan program asset management prerequisites. "
            "Include service life curves by pipe material, risk matrix results, and 20-year CIP "
            "recommendations totaling $214M. Project cost: $1.2M."
        ),
    },

    # =========================================================================
    # PROJECT CLOSE-OUT REPORTS — Energy (4)
    # =========================================================================
    {
        "slug": "closeout_grid_resilience_hurricane_ercot",
        "title": "Project Close-Out Report: ERCOT Coastal Grid Resilience Study — Post-Ida Assessment",
        "domain": "energy",
        "document_type": "project_closeout_report",
        "prompt": (
            "Write a 700–900 word close-out report for a grid resilience study assessing hurricane "
            "vulnerability of coastal Texas transmission infrastructure in the ERCOT region. Scope "
            "included wind fragility modeling for 230kV and 345kV transmission structures, storm "
            "surge inundation mapping of substations, backup power gap analysis for critical "
            "facilities, and resilience investment prioritization. Reference ASCE 7 wind loading, "
            "IEEE 693 seismic standards for substations, NERC reliability standards, and FEMA "
            "Hazus hurricane model. Include estimated outage risk reduction per $1M invested, "
            "priority hardening project list, and FEMA BRIC funding strategy. Study: $1.1M."
        ),
    },
    {
        "slug": "closeout_substation_upgrade_southeast_texas",
        "title": "Project Close-Out Report: Southeast Texas 138kV Substation Modernization",
        "domain": "energy",
        "document_type": "project_closeout_report",
        "prompt": (
            "Write a 700–950 word close-out report for a substation modernization project replacing "
            "aging 138kV switchgear and adding digital protection relays, transformer monitoring "
            "systems, and substation automation at 6 facilities in Southeast Texas. Reference IEEE "
            "C37 protection relay standards, NERC CIP cybersecurity requirements, ASCE 7 equipment "
            "anchorage, and IEC 61850 communication protocols. Include commissioning test results, "
            "cybersecurity compliance outcomes, and O&M cost reduction projections. Contract: $18.4M."
        ),
    },
    {
        "slug": "closeout_solar_interconnection_study_west_texas",
        "title": "Project Close-Out Report: West Texas Solar Farm Interconnection Engineering",
        "domain": "energy",
        "document_type": "project_closeout_report",
        "prompt": (
            "Write a 600–800 word close-out report for an interconnection engineering study for a "
            "300 MW utility-scale solar farm in West Texas (Pecos County) connecting to the ERCOT "
            "transmission grid. Scope included power flow analysis, short circuit study, protection "
            "coordination, and collector system design. Reference ERCOT interconnection procedures, "
            "IEEE 1547 distributed resource standards, NERC FAC-001/002 facility connection "
            "requirements, and NEC for PV system design. Include capacity factor projections, "
            "congestion analysis findings, and required network upgrades. Study: $450K."
        ),
    },
    {
        "slug": "closeout_energy_efficiency_municipal_buildings",
        "title": "Project Close-Out Report: Texas Municipal Building Energy Efficiency Retrofit Program",
        "domain": "energy",
        "document_type": "project_closeout_report",
        "prompt": (
            "Write a 700–900 word close-out report for an energy efficiency retrofit program covering "
            "42 municipal buildings in three Texas cities. Scope included LED lighting, HVAC "
            "optimization, building automation system (BAS) upgrades, and solar PV installations. "
            "Reference ASHRAE 90.1, IECC energy codes, DOE Better Buildings program benchmarks, "
            "and Texas LoanSTAR program requirements. Include verified energy savings (kWh and "
            "therms), simple payback periods by measure type, measured vs. predicted performance "
            "gap analysis, and IIJA funding utilized. Program cost: $12.8M; annual savings: $1.4M."
        ),
    },

    # =========================================================================
    # PROPOSAL TEMPLATES (12)
    # =========================================================================
    {
        "slug": "proposal_template_bridge_inspection",
        "title": "Proposal Template: Bridge Inspection and Condition Assessment Services",
        "domain": "transportation",
        "document_type": "proposal_template",
        "prompt": (
            "Write a 700–1000 word proposal template for bridge inspection and condition assessment "
            "services under NBIS regulations. Include: executive summary placeholder, firm qualifications "
            "section referencing FHWA Bridge Inspector's Reference Manual, AASHTO MBE, and TxDOT "
            "certification requirements; scope of services with underwater inspection, fracture "
            "critical element inspection, and scour assessment protocols; project team structure with "
            "team lead qualifications; schedule (24-month NBIS cycle); and fee structure template. "
            "Make this suitable for a county or state DOT procurement."
        ),
    },
    {
        "slug": "proposal_template_disaster_resilience",
        "title": "Proposal Template: FEMA BRIC Hazard Mitigation Project Development and Application",
        "domain": "environmental",
        "document_type": "proposal_template",
        "prompt": (
            "Write a 700–900 word proposal template for FEMA Building Resilient Infrastructure and "
            "Communities (BRIC) grant application development services. Include scope sections for "
            "benefit-cost analysis (BCA) per FEMA guidance, benefit-cost ratio computation, NEPA "
            "environmental review, and HMA grant application preparation. Reference FEMA HMA guidance "
            "documents, FEMA BCA Toolkit, and the Unified Hazard Mitigation Assistance (HMA) "
            "program requirements. Include deliverables list, timeline for a typical BRIC application "
            "cycle, and fee estimate ranges."
        ),
    },
    {
        "slug": "proposal_template_energy_audit",
        "title": "Proposal Template: Utility Energy Audit and Master Plan",
        "domain": "energy",
        "document_type": "proposal_template",
        "prompt": (
            "Write a 700–900 word proposal template for a utility energy audit and 10-year energy "
            "master plan for a municipal utility district. Include scope covering ASHRAE Level I-III "
            "energy audits, load forecasting, renewable energy feasibility (solar PV, battery storage), "
            "grid interconnection assessment, and IIJA grant eligibility screening. Reference ASHRAE "
            "90.1, DOE Better Buildings, and NERC reliability standards. Include project team bios "
            "placeholder, schedule, and tiered fee option structure."
        ),
    },
    {
        "slug": "proposal_template_desalination_feasibility",
        "title": "Proposal Template: Desalination Feasibility Study — Coastal Texas",
        "domain": "water",
        "document_type": "proposal_template",
        "prompt": (
            "Write an 800–1100 word proposal template for a desalination feasibility study for a "
            "coastal Texas water utility facing supply shortfalls identified in the TWDB 2026 State "
            "Water Plan. Include scope sections for: source water characterization (seawater and "
            "brackish groundwater), technology screening (SWRO vs BWRO vs electrodialysis), "
            "concentrate management alternatives, capital and O&M cost modeling, energy cost "
            "analysis, water rights and TCEQ permitting pathway, and TWDB SWIFT financing strategy. "
            "Reference AWWA desalination best practices, TWDB 2026 Plan Region L/N coastal "
            "scenarios, EPA concentrate disposal guidance, and Texas Water Code. Include team "
            "qualifications template, 18-month schedule, and fee range $350K–$900K."
        ),
    },
    {
        "slug": "proposal_template_aquifer_storage_recovery",
        "title": "Proposal Template: Aquifer Storage and Recovery (ASR) Design and Permitting",
        "domain": "water",
        "document_type": "proposal_template",
        "prompt": (
            "Write a 750–1000 word proposal template for ASR project design and permitting services "
            "in Texas. Scope includes hydrogeological investigation, TCEQ Class V UIC well permitting, "
            "pilot injection and recovery testing, native groundwater and recharged water quality "
            "compatibility analysis, full-scale design, and Groundwater Conservation District "
            "coordination. Reference TWDB ASR guidance manual, Texas Water Code Chapter 27, TCEQ "
            "UIC rules (30 TAC Chapter 331), AWWA ASR guidelines, and TWDB 2026 State Water Plan "
            "ASR strategies for drought-prone regions. Include qualifications, project phasing, "
            "regulatory schedule, and fee breakdown."
        ),
    },
    {
        "slug": "proposal_template_water_reuse_program",
        "title": "Proposal Template: Potable Water Reuse Program Planning and Design",
        "domain": "water",
        "document_type": "proposal_template",
        "prompt": (
            "Write an 800–1000 word proposal template for a potable water reuse feasibility and "
            "design program for a Texas municipality. Include scope for indirect potable reuse (IPR) "
            "and direct potable reuse (DPR) alternatives analysis, advanced treatment train design "
            "(MF/RO/UV-AOP), regulatory pathway under TCEQ Chapter 210 and proposed DPR rules, "
            "public engagement strategy, and CWSRF financing strategy. Reference EPA Guidelines "
            "for Water Reuse, AWWA potable reuse framework, TCEQ reuse regulations, and TWDB "
            "2026 State Water Plan recommended reuse strategies. Include team structure, 24-month "
            "phased schedule, and fee range."
        ),
    },
    {
        "slug": "proposal_template_water_conservation_program",
        "title": "Proposal Template: Municipal Water Conservation Program Development",
        "domain": "water",
        "document_type": "proposal_template",
        "prompt": (
            "Write a 700–900 word proposal template for a municipal water conservation program "
            "development engagement. Scope includes: demand analysis and water audit, best management "
            "practice (BMP) screening and cost-effectiveness analysis, tiered rate structure review, "
            "TCEQ Conservation Plan requirements compliance, landscape irrigation ordinance drafting, "
            "and TWDB financial assistance prerequisites. Reference TWDB Water Conservation Best "
            "Management Practices Guide, AWWA M52 Water Conservation Programs, TCEQ 30 TAC Chapter "
            "288 conservation plan rules, and IIJA water efficiency grant programs. Fee range: $120K–$280K."
        ),
    },
    {
        "slug": "proposal_template_highway_feasibility",
        "title": "Proposal Template: Highway Corridor Feasibility and Environmental Study",
        "domain": "transportation",
        "document_type": "proposal_template",
        "prompt": (
            "Write a 700–950 word proposal template for a highway corridor feasibility study and "
            "NEPA environmental assessment. Include scope for traffic analysis, alternatives "
            "development, AASHTO Green Book geometric design, hydraulic analysis, Section 404/401 "
            "permitting, cultural resources survey (Section 106), and public involvement. Reference "
            "FHWA NEPA process, TxDOT Environmental Manual, AASHTO Policy on Geometric Design, "
            "and FHWA MAP-21/IIJA planning requirements. Include schedule, team structure, and fee."
        ),
    },
    {
        "slug": "proposal_template_water_master_plan",
        "title": "Proposal Template: Regional Water System Master Plan",
        "domain": "water",
        "document_type": "proposal_template",
        "prompt": (
            "Write a 750–1000 word proposal template for a regional water system master plan. "
            "Scope includes population and demand projections to 2080, water supply alternatives "
            "analysis, infrastructure condition assessment, hydraulic model development (EPANET or "
            "WaterGEMS), CIP prioritization, rate study, and TWDB SWIFT financing package preparation. "
            "Reference AWWA M50 Water Resources Planning, TCEQ Chapter 290 capacity development "
            "criteria, TWDB 2026 State Water Plan regional context, and EPA drinking water "
            "infrastructure needs survey methodology. Fee range: $280K–$650K."
        ),
    },
    {
        "slug": "proposal_template_grid_resilience",
        "title": "Proposal Template: Electric Grid Resilience Assessment and Hardening Plan",
        "domain": "energy",
        "document_type": "proposal_template",
        "prompt": (
            "Write a 700–900 word proposal template for an electric grid resilience assessment "
            "and hardening plan for a Texas electric cooperative or municipal utility. Scope covers "
            "risk and vulnerability assessment, consequence analysis for transmission outage scenarios, "
            "hardening alternatives (underground cable, steel pole replacement, distributed generation), "
            "IIJA grid resilience grant eligibility screening, and 10-year investment plan. Reference "
            "NERC reliability standards, IEEE 693, ASCE 7 extreme wind loading, and DOE Grid "
            "Resilience Formula Grants program. Include team, schedule, and fee."
        ),
    },
    {
        "slug": "proposal_template_environmental_assessment",
        "title": "Proposal Template: Phase I and Phase II Environmental Site Assessment",
        "domain": "environmental",
        "document_type": "proposal_template",
        "prompt": (
            "Write a 600–800 word proposal template for Phase I and Phase II Environmental Site "
            "Assessments (ESAs) for infrastructure project right-of-way acquisition. Scope includes "
            "ASTM E1527-21 Phase I ESA, ASTM E1903 Phase II sampling protocol, TCEQ voluntary "
            "cleanup program eligibility assessment, and remediation cost estimation. Reference "
            "ASTM standards, EPA All Appropriate Inquiries (AAI) rule, TCEQ remediation regulations "
            "(30 TAC Chapter 333), and Texas Brownfields program. Include turnaround times, "
            "laboratory partners, and unit pricing structure."
        ),
    },
    {
        "slug": "proposal_template_flood_risk_assessment",
        "title": "Proposal Template: Flood Risk and Resilience Assessment",
        "domain": "environmental",
        "document_type": "proposal_template",
        "prompt": (
            "Write a 700–900 word proposal template for a community flood risk and resilience "
            "assessment. Scope includes HEC-RAS 2D hydraulic modeling, FEMA Hazus loss estimation, "
            "critical facility vulnerability mapping, nature-based solutions alternatives, FEMA "
            "Community Rating System (CRS) improvement strategy, and FEMA BRIC application support. "
            "Reference FEMA NFIP regulations, ASCE 7 flood load design, FHWA hydraulic engineering "
            "circulars, and USACE Levee Safety Program guidelines. Fee range: $180K–$420K."
        ),
    },

    # =========================================================================
    # COST ESTIMATION GUIDES (10)
    # =========================================================================
    {
        "slug": "cost_guide_bridge_rehab_concrete",
        "title": "Cost Estimation Guide: Concrete Bridge Rehabilitation — Texas",
        "domain": "transportation",
        "document_type": "cost_estimation_guide",
        "prompt": (
            "Write a 700–1000 word cost estimation guide for concrete bridge rehabilitation in Texas. "
            "Include cost-per-square-foot ranges for deck replacement, deck overlay (LMC, HES), "
            "substructure concrete repair, pier jacketing, bearing replacement, railing upgrade, "
            "and scour countermeasures. Reference RSMeans, TxDOT bid tabs (2022–2024 statewide "
            "averages), AASHTO LRFD rehabilitation provisions, and FHWA cost index data. Include "
            "a table of typical unit costs with low/median/high ranges, mobilization factors for "
            "rural vs. urban sites, and escalation guidance. Note contractor markup assumptions."
        ),
    },
    {
        "slug": "cost_guide_bridge_rehab_steel",
        "title": "Cost Estimation Guide: Steel Bridge Rehabilitation — Painting and Structural Repair",
        "domain": "transportation",
        "document_type": "cost_estimation_guide",
        "prompt": (
            "Write a 700–950 word cost estimation guide for steel bridge rehabilitation including "
            "full containment paint removal, lead paint abatement, new coating system application "
            "(SSPC SP-10, zinc primer, epoxy intermediate, urethane topcoat), and structural steel "
            "repair. Reference SSPC, NACE, FHWA steel bridge maintenance guidelines, and TxDOT "
            "bridge painting specifications. Provide unit costs for lead paint abatement per ton "
            "of steel, coating per square foot, flange/web cover plate installation, and rivet "
            "replacement. Include environmental regulatory compliance cost factors for Texas Gulf "
            "Coast air quality permit requirements."
        ),
    },
    {
        "slug": "cost_guide_bridge_new_construction",
        "title": "Cost Estimation Guide: New Highway Bridge Construction — Unit Cost Reference",
        "domain": "transportation",
        "document_type": "cost_estimation_guide",
        "prompt": (
            "Write an 800–1000 word cost estimation guide for new highway bridge construction in "
            "Texas. Provide cost per square foot ranges by structure type: prestressed concrete "
            "box beam, prestressed concrete I-beam, CIP concrete box girder, steel plate girder, "
            "and pedestrian bridge. Include foundation cost factors (driven pile, drilled shaft, "
            "spread footing), wing wall and approach slab costs, traffic control allowances, and "
            "hydraulic fill/erosion control. Reference TxDOT average bid data (2020–2024), RSMeans "
            "Heavy Construction, and AASHTO LRFD design assumptions. Include escalation guidance "
            "for 2025 and 2026 construction."
        ),
    },
    {
        "slug": "cost_guide_water_treatment_conventional",
        "title": "Cost Estimation Guide: Conventional Surface Water Treatment Plant — Construction Costs",
        "domain": "water",
        "document_type": "cost_estimation_guide",
        "prompt": (
            "Write an 800–1000 word cost estimation guide for conventional surface water treatment "
            "plant construction in Texas. Include cost curves by capacity (1 MGD to 50 MGD) for "
            "coagulation/flocculation, sedimentation, filtration, disinfection (chlorine, UV, ozone), "
            "chemical storage, clearwell, high-service pumping, and SCADA systems. Reference AWWA "
            "M49 (Water Treatment Plant Hydraulics), EPA construction cost indices, TWDB project "
            "data from SWIFT loan program, and ENR construction cost index. Include a capacity "
            "factor curve, O&M cost per thousand gallons by plant size, and TCEQ design criteria "
            "impact on cost (Chapter 290 requirements). Provide 2024 Texas-specific cost multipliers."
        ),
    },
    {
        "slug": "cost_guide_water_treatment_membrane",
        "title": "Cost Estimation Guide: Membrane Filtration and Reverse Osmosis Treatment — Cost Reference",
        "domain": "water",
        "document_type": "cost_estimation_guide",
        "prompt": (
            "Write an 800–1000 word cost estimation guide for membrane filtration (MF/UF) and "
            "reverse osmosis (RO) water treatment systems in Texas. Cover brackish groundwater RO, "
            "surface water MF/UF pretreatment, and RO concentrate management (deep well injection, "
            "evaporation ponds, concentrate discharge). Reference AWWA desalination cost tools, "
            "EPA WaterSense data, TWDB 2026 State Water Plan cost assumptions for desalination "
            "strategies, and WRRF membrane market data. Provide capital cost per installed MGD "
            "for MF, BWRO, and SWRO; energy cost per acre-foot; and concentrate disposal cost "
            "ranges. Include Texas-specific regulatory cost factors (TCEQ Chapter 290, UIC Class I)."
        ),
    },
    {
        "slug": "cost_guide_water_treatment_reuse",
        "title": "Cost Estimation Guide: Advanced Water Purification for Potable Reuse",
        "domain": "water",
        "document_type": "cost_estimation_guide",
        "prompt": (
            "Write a 700–900 word cost estimation guide for advanced water purification (AWP) "
            "facilities for indirect or direct potable reuse. Include capital and O&M costs for "
            "MF/UF, RO, UV/AOP, and GAC polishing trains. Reference AWWA potable reuse framework, "
            "WRF Reuse Economic Analysis research, EPA 2012 Guidelines for Water Reuse, and TWDB "
            "reuse cost data. Provide cost per acre-foot of treated water by system capacity "
            "(1–20 MGD range), energy benchmarks, and chemical cost drivers. Include Texas "
            "regulatory cost factors for TCEQ Chapter 210 compliance and public engagement budgeting."
        ),
    },
    {
        "slug": "cost_guide_pipeline_water_transmission",
        "title": "Cost Estimation Guide: Water Transmission Pipeline — Construction Unit Costs",
        "domain": "water",
        "document_type": "cost_estimation_guide",
        "prompt": (
            "Write an 800–1000 word cost estimation guide for water transmission pipeline construction "
            "in Texas. Provide unit cost ranges by diameter (8-inch to 72-inch) and pipe material "
            "(DIP, AWWA C200 steel, PCCP, HDPE, PVC) for open-cut and trenchless (HDD, pipe "
            "jacking, microtunneling) installation. Reference AWWA pipeline design standards "
            "(C150, C200, C300, C900/905), RSMeans Site Work and Landscape Cost Data, TxDOT "
            "row crossing permit cost assumptions, and TWDB funded project cost data. Include "
            "cathodic protection, testing, and commissioning cost allowances; Texas soil type "
            "cost factors; and river crossing premium estimates."
        ),
    },
    {
        "slug": "cost_guide_pipeline_wastewater_force_main",
        "title": "Cost Estimation Guide: Wastewater Force Main and Lift Station Construction Costs",
        "domain": "water",
        "document_type": "cost_estimation_guide",
        "prompt": (
            "Write a 700–900 word cost estimation guide for wastewater force main and lift station "
            "construction in Texas. Provide cost ranges for lift stations by design flow (50 gpm to "
            "5000 gpm), including wet well, dry pit, pump selection, electrical, SCADA, and site "
            "work. Force main unit costs by diameter (4-inch to 24-inch) in DIP and HDPE. Reference "
            "AWWA M28, Ten State Standards (Recommended Standards for Wastewater Facilities), "
            "TCEQ Chapter 217 wastewater design rules, and ENR cost data. Include Texas red clay "
            "soil surcharge factors and utility conflict allowances for urban projects."
        ),
    },
    {
        "slug": "cost_guide_grid_resilience_hardening",
        "title": "Cost Estimation Guide: Electric Grid Resilience Hardening — Unit Cost Reference",
        "domain": "energy",
        "document_type": "cost_estimation_guide",
        "prompt": (
            "Write a 700–900 word cost estimation guide for electric grid hardening and resilience "
            "investments. Include unit costs for: steel monopole replacement of wood pole lines "
            "(per mile, by voltage class), transmission line undergrounding (per mile, 69kV/138kV), "
            "substation flood barrier and elevation projects (per substation), transformer spill "
            "containment, and distributed generation backup (generator sets per kW). Reference "
            "NERC reliability investment benchmarks, DOE Grid Resilience Formula Grant cost "
            "eligibility data, ASCE 7 extreme wind load design cost premium, and EEI storm "
            "hardening best practices. Provide Texas Gulf Coast hurricane zone cost multipliers "
            "vs. inland Texas baseline."
        ),
    },
    {
        "slug": "cost_guide_grid_solar_battery_storage",
        "title": "Cost Estimation Guide: Utility-Scale Solar PV and Battery Storage — 2024 Texas",
        "domain": "energy",
        "document_type": "cost_estimation_guide",
        "prompt": (
            "Write a 700–900 word cost estimation guide for utility-scale solar PV and co-located "
            "battery energy storage system (BESS) development in Texas. Provide capital cost ranges "
            "per MW-AC for solar (fixed tilt vs. single-axis tracking), per MWh for BESS (4-hour "
            "duration), and combined solar+storage. Reference NREL Annual Technology Baseline "
            "(2024), ERCOT interconnection cost data, Texas land cost premiums, and ITC/PTC "
            "incentive impact on effective costs post-IRA 2022. Include soft cost breakdown "
            "(permitting, interconnection, development) and O&M annual cost per MW."
        ),
    },

    # =========================================================================
    # ENGINEERING STANDARDS SUMMARIES (8)
    # =========================================================================
    {
        "slug": "standards_aashto_lrfd_bridge_design",
        "title": "Engineering Standards Summary: AASHTO LRFD Bridge Design Specifications — 9th Edition",
        "domain": "transportation",
        "document_type": "engineering_standard_summary",
        "prompt": (
            "Write a 700–1000 word engineering standards summary of AASHTO LRFD Bridge Design "
            "Specifications, 9th Edition. Cover: load combinations (Strength I–V, Service I–IV, "
            "Fatigue I–II, Extreme Event I–II), HL-93 live load model, resistance factors by "
            "material and limit state, scour design requirements (HEC-18 integration), seismic "
            "design zone mapping for Texas, and key changes from 8th to 9th edition. Explain how "
            "this standard integrates with TxDOT Bridge Design Manual. Include practical notes "
            "for Texas bridge engineers on foundation design in expansive soils and scour critical "
            "designations. Audience: mid-level structural engineers."
        ),
    },
    {
        "slug": "standards_asce_7_wind_flood_seismic",
        "title": "Engineering Standards Summary: ASCE 7-22 — Wind, Flood, and Seismic Loads for Texas Infrastructure",
        "domain": "transportation",
        "document_type": "engineering_standard_summary",
        "prompt": (
            "Write a 700–950 word engineering standards summary of ASCE 7-22 focusing on its "
            "application to Texas infrastructure. Cover: wind speed maps and exposure categories "
            "for Gulf Coast vs. Panhandle regions, design flood levels and freeboard requirements, "
            "seismic design category determination for Texas (generally low seismic), and load "
            "combinations for infrastructure design. Explain differences from ASCE 7-16 relevant "
            "to Texas practice. Reference FEMA P-58, TxDOT structural design guidance, and ICC "
            "2021 code adoption status in Texas. Audience: licensed Texas PE."
        ),
    },
    {
        "slug": "standards_epa_sdwa_drinking_water",
        "title": "Engineering Standards Summary: EPA Safe Drinking Water Act — Regulatory Framework",
        "domain": "water",
        "document_type": "engineering_standard_summary",
        "prompt": (
            "Write a 750–1000 word engineering standards summary of the EPA Safe Drinking Water "
            "Act (SDWA) regulatory framework as it applies to Texas community water systems. Cover: "
            "National Primary Drinking Water Regulations (NPDWRs) key rules (TCR/RTCR, Lead and "
            "Copper Rule Revisions, Groundwater Rule, Surface Water Treatment Rule), reporting and "
            "monitoring requirements, TCEQ primacy role and Chapter 290 relationship, violation "
            "classification and enforcement, and public notification requirements. Reference SDWA "
            "PWSS program, EPA SDWIS database, and recent LCR revisions effective 2024. Audience: "
            "Texas public water system operators and engineers."
        ),
    },
    {
        "slug": "standards_twdb_design_criteria",
        "title": "Engineering Standards Summary: TWDB Design Criteria for Public Drinking Water Systems",
        "domain": "water",
        "document_type": "engineering_standard_summary",
        "prompt": (
            "Write a 700–950 word engineering standards summary of TWDB and TCEQ design criteria "
            "for Texas public drinking water systems. Cover: TCEQ Chapter 290 design criteria "
            "(source water adequacy, treatment capacity, storage requirements), fire flow "
            "requirements, pressure zone standards, emergency storage sizing, well construction "
            "standards, and TWDB SWIFT loan program technical review requirements. Reference "
            "TCEQ 30 TAC Chapter 290, AWWA standards for pipes/valves/pumps, and TWDB Financial "
            "Assistance Program Rules. Include a summary table of key design parameters (min "
            "pressure, storage per capita, treatment redundancy). Audience: Texas PE/EIT."
        ),
    },
    {
        "slug": "standards_awwa_distribution_systems",
        "title": "Engineering Standards Summary: AWWA Standards for Water Distribution Systems",
        "domain": "water",
        "document_type": "engineering_standard_summary",
        "prompt": (
            "Write a 700–900 word engineering standards summary of key AWWA standards applicable "
            "to water distribution system design and operation. Cover: pipe material standards "
            "(C104/A21.4, C110/A21.10, C150/A21.50, C900, C905), valve standards (C500, C504, "
            "C509), fire hydrant (C502/C503), water meter (C700), and pressure testing (C600). "
            "Reference AWWA M11 (Steel Pipe), M23 (PVC Pipe), M17 (Installation/Sampling), and "
            "M31 (Distribution System Requirements for Fire Protection). Include Texas-specific "
            "adoption notes and TCEQ Chapter 290 cross-references. Audience: distribution "
            "system designers and operators."
        ),
    },
    {
        "slug": "standards_aashto_bridge_evaluation",
        "title": "Engineering Standards Summary: AASHTO Manual for Bridge Evaluation — Load Rating",
        "domain": "transportation",
        "document_type": "engineering_standard_summary",
        "prompt": (
            "Write a 700–950 word engineering standards summary of the AASHTO Manual for Bridge "
            "Evaluation (MBE), 3rd Edition, focusing on load rating practices. Cover: Load Factor "
            "Rating (LFR), Load and Resistance Factor Rating (LRFR), condition factor selection, "
            "load posting thresholds, inventory vs. operating rating, AASHTO legal loads, Texas "
            "permit load vehicles, and fatigue evaluation Chapter 7. Reference FHWA load rating "
            "policy memo, TxDOT Bridge Design Manual load rating chapter, and NBI load rating "
            "coding requirements. Include worked example structure for a prestressed concrete "
            "beam bridge. Audience: bridge engineers performing NBIS inspections."
        ),
    },
    {
        "slug": "standards_awwa_asset_management",
        "title": "Engineering Standards Summary: AWWA Asset Management Framework for Water Utilities",
        "domain": "water",
        "document_type": "engineering_standard_summary",
        "prompt": (
            "Write a 700–900 word engineering standards summary of the AWWA utility asset "
            "management framework. Cover: five core questions of asset management (what assets, "
            "condition, risk, best alternative, sustainable funding), level of service definition, "
            "risk-based prioritization, service life modeling by asset class, lifecycle cost "
            "analysis, and regulatory connection to EPA SDWA capacity development. Reference "
            "AWWA AM09 (Asset Management Program for Water & Wastewater Utilities), EPA CUPSS "
            "tool, and TWDB SWIFT program asset management prerequisite requirements. Include "
            "a summary of minimum AM program elements acceptable to TWDB reviewers. Audience: "
            "water utility managers and engineers."
        ),
    },
    {
        "slug": "standards_nerc_reliability_energy",
        "title": "Engineering Standards Summary: NERC Reliability Standards for Bulk Electric System",
        "domain": "energy",
        "document_type": "engineering_standard_summary",
        "prompt": (
            "Write a 700–950 word engineering standards summary of NERC reliability standards "
            "relevant to Texas bulk electric system infrastructure. Cover: FAC-001/002 (Facility "
            "Connection Requirements), TPL-001 (Transmission Planning), PRC-002 (Disturbance "
            "Monitoring), CIP-002 through CIP-013 (cybersecurity critical infrastructure "
            "protection), EOP-004 (Event Reporting), and ERCOT-specific protocols that supplement "
            "NERC standards in Texas. Reference NERC Reliability Guidelines, ERCOT Nodal "
            "Protocols, and FERC Order 693 reliability standards requirements. Audience: "
            "transmission planners and substation engineers."
        ),
    },

    # =========================================================================
    # RISK ASSESSMENT FRAMEWORKS (8)
    # =========================================================================
    {
        "slug": "risk_framework_scour_bridges_texas",
        "title": "Risk Assessment Framework: Bridge Scour — Texas River Crossings",
        "domain": "transportation",
        "document_type": "risk_assessment_framework",
        "prompt": (
            "Write a 700–1000 word risk assessment framework for bridge scour on Texas river "
            "crossings. Cover: scour criticality classification (scour critical vs. scour "
            "susceptible vs. low risk), Texas flood hydrology drivers (flash flood potential, "
            "Brazos/Trinity/Colorado basin characteristics), foundation type vulnerability "
            "(spread footing > drilled shaft > driven pile), HEC-18 live bed scour calculation "
            "overview, channel migration assessment, and countermeasure selection (riprap, "
            "sheet piling, pier extension). Reference FHWA HEC-18, AASHTO LRFD Article 2.6.4, "
            "TxDOT hydraulic design manual, and NBIS scour inspection requirements. Include a "
            "risk matrix (likelihood x consequence) with scoring criteria and action thresholds."
        ),
    },
    {
        "slug": "risk_framework_scour_monitoring",
        "title": "Risk Assessment Framework: Real-Time Scour Monitoring Programs",
        "domain": "transportation",
        "document_type": "risk_assessment_framework",
        "prompt": (
            "Write a 700–900 word risk assessment framework for establishing real-time scour "
            "monitoring programs on scour-critical Texas bridges. Cover: sensor technology "
            "options (magnetic sliding collar, sonar, MEMS tiltmeter), alert threshold setting "
            "methodology, emergency action plan (EAP) trigger levels, data management and "
            "telemetry to TMOC, and maintenance program design. Reference FHWA LTBP scour "
            "monitoring research, TxDOT hydraulic bridge inspection manual, USGS stream gauge "
            "integration guidance, and AASHTO bridge owner scour monitoring best practices. "
            "Include cost-benefit framework for prioritizing monitoring installations."
        ),
    },
    {
        "slug": "risk_framework_seismic_infrastructure",
        "title": "Risk Assessment Framework: Seismic Risk for Infrastructure — Texas Context",
        "domain": "transportation",
        "document_type": "risk_assessment_framework",
        "prompt": (
            "Write a 700–900 word risk assessment framework for seismic risk assessment of "
            "infrastructure in Texas. Explain the generally low seismic hazard in Texas per "
            "USGS National Seismic Hazard Maps, the exception of induced seismicity in West "
            "Texas injection well fields and DFW Metroplex, and how ASCE 7-22 Seismic Design "
            "Categories A and B apply to most Texas infrastructure. Cover: site class "
            "determination, spectral acceleration parameters, bridge retrofit screening "
            "methodology per FHWA Seismic Retrofitting Manual, and risk prioritization for "
            "essential facilities. Reference AASHTO Guide Specifications for LRFD Seismic "
            "Bridge Design and ASCE 41 for existing building assessment."
        ),
    },
    {
        "slug": "risk_framework_flood_infrastructure",
        "title": "Risk Assessment Framework: Flood Risk for Critical Infrastructure",
        "domain": "environmental",
        "document_type": "risk_assessment_framework",
        "prompt": (
            "Write a 700–950 word risk assessment framework for flood risk assessment of "
            "critical infrastructure — bridges, water treatment plants, pump stations, and "
            "substations — in Texas. Cover: FEMA 1% and 0.2% annual chance floodplain "
            "identification, freeboard requirements by asset type, climate change flood "
            "frequency adjustment methodology, HEC-RAS 2D inundation mapping, and resilience "
            "design standards (Atlas 14 rainfall depths, ASCE 7 flood loads). Reference FEMA "
            "NFIP regulations, FHWA design flood criteria, TCEQ wastewater facility flood "
            "protection requirements, and NERC substation flood resilience standards. Include "
            "a risk matrix and adaptation measure cost-effectiveness methodology."
        ),
    },
    {
        "slug": "risk_framework_drought_water_supply",
        "title": "Risk Assessment Framework: Drought Risk for Municipal Water Supplies — Texas",
        "domain": "water",
        "document_type": "risk_assessment_framework",
        "prompt": (
            "Write a 750–1000 word risk assessment framework for drought risk to municipal water "
            "supplies in Texas. Cover: TWDB water availability model data interpretation, "
            "historical drought of record (1950s drought vs. 2011 drought), reservoir yield "
            "analysis under drought conditions, aquifer sustainable yield under multi-year "
            "drought, supply-demand gap analysis methodology per TWDB 2026 State Water Plan "
            "approach, and trigger level setting for drought contingency plans. Reference "
            "TCEQ 30 TAC Chapter 288 Drought Contingency Plan requirements, TWDB 2026 State "
            "Water Plan shortage projections by region, and TexasWaterTracker data sources. "
            "Include a 5-level drought response framework with action triggers."
        ),
    },
    {
        "slug": "risk_framework_water_supply_resilience",
        "title": "Risk Assessment Framework: Water Supply System Resilience Assessment",
        "domain": "water",
        "document_type": "risk_assessment_framework",
        "prompt": (
            "Write a 700–950 word risk assessment framework for assessing water supply system "
            "resilience. Cover: single-source dependency risk, interconnect availability, "
            "emergency storage adequacy (TCEQ minimum requirements vs. resilience targets), "
            "cyber vulnerability of SCADA systems per EPA water sector guidelines, and "
            "consequence analysis for supply interruption by customer class (hospitals, "
            "industrial, residential). Reference AWWA J100 Risk and Resilience Management "
            "standard, EPA America's Water Infrastructure Act (AWIA 2018) risk and resilience "
            "assessment requirements, and TWDB emergency planning guidance. Include a "
            "resilience scoring matrix and improvement road map template."
        ),
    },
    {
        "slug": "risk_framework_climate_resilience_transportation",
        "title": "Risk Assessment Framework: Climate Resilience for Transportation Infrastructure",
        "domain": "transportation",
        "document_type": "risk_assessment_framework",
        "prompt": (
            "Write a 700–950 word risk assessment framework for climate resilience of "
            "transportation infrastructure in Texas. Cover: sea level rise and storm surge "
            "projections for Gulf Coast (NOAA Technical Report), extreme precipitation trend "
            "data for Texas, increased wildfire risk to roadway corridors, extreme heat impact "
            "on pavement and bridge expansion joints, and FHWA climate vulnerability assessment "
            "methodology. Reference FHWA Climate Change and Extreme Weather Vulnerability "
            "Assessment Framework, AASHTO climate adaptation guidelines, TxDOT climate risk "
            "management program, and IIJA climate resilience requirements for Mega Projects. "
            "Include an asset criticality x climate exposure matrix."
        ),
    },
    {
        "slug": "risk_framework_climate_resilience_water",
        "title": "Risk Assessment Framework: Climate Resilience for Water Infrastructure",
        "domain": "water",
        "document_type": "risk_assessment_framework",
        "prompt": (
            "Write a 700–950 word risk assessment framework for climate resilience of water "
            "and wastewater infrastructure. Cover: increased drought frequency impact on "
            "reservoir yields and groundwater, extreme precipitation impact on treatment plant "
            "flooding and combined sewer overflows, temperature increase impact on water "
            "demand and treatment chemistry, saltwater intrusion into coastal aquifers, and "
            "supply portfolio diversification strategies. Reference TWDB 2026 State Water Plan "
            "climate scenario analysis, EPA Climate Resilience Evaluation and Awareness Tool "
            "(CREAT), AWWA climate change and water sector guidance, and TCEQ Climate "
            "Adaptation Plan. Include a water utility climate vulnerability scorecard."
        ),
    },

    # =========================================================================
    # CLIENT BRIEFING TEMPLATES (6)
    # =========================================================================
    {
        "slug": "briefing_template_bridge_condition_summary",
        "title": "Client Briefing Template: Bridge Portfolio Condition Summary",
        "domain": "transportation",
        "document_type": "client_briefing_template",
        "prompt": (
            "Write a 600–800 word client briefing template for presenting bridge portfolio "
            "condition assessment results to a county commissioner or DOT official. Include: "
            "executive summary section with key metrics (% structurally deficient, average "
            "sufficiency rating, number of scour critical structures), a condition rating "
            "distribution summary table, top 5 priority structures with rationale, recommended "
            "5-year CIP with cost ranges, available federal funding programs (FHWA BRRP, RAISE "
            "grants, IIJA bridge formula funds), and next steps. Use plain language accessible "
            "to non-engineers while including correct technical terminology."
        ),
    },
    {
        "slug": "briefing_template_fema_disaster_analysis",
        "title": "Client Briefing Template: FEMA Disaster Declaration Analysis and Recovery Strategy",
        "domain": "environmental",
        "document_type": "client_briefing_template",
        "prompt": (
            "Write a 600–800 word client briefing template for presenting FEMA disaster "
            "declaration history analysis to a county emergency manager or infrastructure "
            "owner. Include: summary of declarations in the county/region over 10 years, "
            "repeat incident types and trend analysis, public assistance grants received vs. "
            "available, Hazard Mitigation Grant Program opportunities identified, FEMA BRIC "
            "competitive grant positioning, and recommended hazard mitigation investments with "
            "benefit-cost ratio ranges. Include a timeline graphic placeholder and a prioritized "
            "action matrix."
        ),
    },
    {
        "slug": "briefing_template_water_plan_strategy",
        "title": "Client Briefing Template: TWDB 2026 State Water Plan — Regional Strategy Summary",
        "domain": "water",
        "document_type": "client_briefing_template",
        "prompt": (
            "Write a 700–900 word client briefing template for presenting TWDB 2026 State "
            "Water Plan findings to a municipal water utility board or county commissioners. "
            "Cover: the $174B statewide funding gap context, the region-specific supply deficit "
            "projections through 2080, recommended strategies relevant to the client's region "
            "(desalination, ASR, conservation, reuse), SWIFT loan program parameters and "
            "eligibility, CWSRF/DWSRF grant and loan availability, and a recommended project "
            "development roadmap. Reference specific TWDB planning region context (A–P) and "
            "use accessible language for elected officials."
        ),
    },
    {
        "slug": "briefing_template_energy_grid_resilience",
        "title": "Client Briefing Template: Electric Grid Resilience Assessment Findings",
        "domain": "energy",
        "document_type": "client_briefing_template",
        "prompt": (
            "Write a 600–800 word client briefing template for presenting electric grid "
            "resilience assessment findings to a utility board or municipal leadership. Include: "
            "current system vulnerability summary (% overhead lines, substation flood exposure, "
            "transformer age profile), top 5 resilience risks with likelihood and consequence "
            "ratings, recommended hardening investments with cost ranges, DOE Grid Resilience "
            "Formula Grant eligibility assessment, ERCOT compliance requirements, and 5-year "
            "investment roadmap. Use accessible language and include a risk matrix visual placeholder."
        ),
    },
    {
        "slug": "briefing_template_sdwa_compliance",
        "title": "Client Briefing Template: Safe Drinking Water Act Compliance Status and Action Plan",
        "domain": "water",
        "document_type": "client_briefing_template",
        "prompt": (
            "Write a 600–800 word client briefing template for presenting SDWA compliance "
            "status to a water utility board. Include: summary of current violations by rule "
            "(TCR, LCR, chemical MCLs), TCEQ enforcement status, public notification "
            "obligations and timeline, corrective action alternatives with cost estimates, "
            "TWDB SWIFT or DWSRF emergency financing options, and recommended compliance "
            "timeline. Use plain language appropriate for elected utility board members while "
            "accurately representing regulatory requirements per TCEQ Chapter 290."
        ),
    },
    {
        "slug": "briefing_template_climate_risk_summary",
        "title": "Client Briefing Template: Infrastructure Climate Risk Summary for Executive Leadership",
        "domain": "environmental",
        "document_type": "client_briefing_template",
        "prompt": (
            "Write a 700–900 word client briefing template for presenting infrastructure "
            "climate risk findings to a C-suite or county judge/mayor audience. Cover: "
            "top 3 climate risks facing the client's asset portfolio (flood, drought, extreme "
            "heat — tailored to Texas context), financial exposure estimates, federal funding "
            "programs available (FEMA BRIC, IIJA resilience grants, EPA CWSRF climate "
            "set-aside), regulatory drivers (FEMA CRS, TCEQ drought contingency plan, NERC "
            "reliability), and a recommended immediate action matrix. Use accessible executive "
            "language — no engineering jargon without definition."
        ),
    },

    # =========================================================================
    # WATER-SPECIFIC MARKET INTELLIGENCE (10)
    # =========================================================================
    {
        "slug": "market_intel_desalination_technology",
        "title": "Market Intelligence: Desalination Technology Overview — Texas Applications",
        "domain": "water",
        "document_type": "market_intelligence",
        "prompt": (
            "Write a 700–1000 word market intelligence document on desalination technology "
            "for Texas water applications. Cover: reverse osmosis (SWRO vs. BWRO) technology "
            "state of the art, energy recovery device advances (isobaric devices), low-pressure "
            "RO for brackish groundwater, forward osmosis and electrodialysis as emerging "
            "technologies, concentrate management options for inland Texas (deep well injection "
            "under TCEQ UIC Class I, evaporation ponds, zero liquid discharge). Reference TWDB "
            "2026 State Water Plan desalination strategies, Texas Desalination Association "
            "activity, AWWA desalination membrane market report, and major Texas facility "
            "examples (Kay Bailey Hutchison, Corpus Christi brackish program). Include "
            "cost trend analysis: $/acre-foot desalinated water 2015–2024."
        ),
    },
    {
        "slug": "market_intel_aquifer_storage_recovery",
        "title": "Market Intelligence: Aquifer Storage and Recovery (ASR) in Texas",
        "domain": "water",
        "document_type": "market_intelligence",
        "prompt": (
            "Write a 700–900 word market intelligence document on ASR as a water supply "
            "strategy in Texas. Cover: ASR suitability mapping (Edwards, Trinity, Carrizo-"
            "Wilcox Aquifer targets), TCEQ UIC Class V permitting pathway, Groundwater "
            "Conservation District coordination requirements, recovery efficiency benchmarks "
            "from Texas pilot programs, water quality degradation risks and mitigation, and "
            "the San Antonio Water System ASR program as a case study. Reference TWDB 2026 "
            "State Water Plan ASR strategies by planning region, TWDB ASR guidance manual, "
            "and AWWA ASR market sizing. Discuss drought cycle optimization for ASR systems "
            "in a Texas climate context."
        ),
    },
    {
        "slug": "market_intel_brackish_groundwater_treatment",
        "title": "Market Intelligence: Brackish Groundwater Treatment — Texas Market Opportunities",
        "domain": "water",
        "document_type": "market_intelligence",
        "prompt": (
            "Write a 700–950 word market intelligence document on brackish groundwater "
            "treatment opportunities in Texas. Cover: brackish aquifer extent (Carrizo-Wilcox, "
            "Gulf Coast Aquifer System, Ogallala saline zone), TDS concentration ranges and "
            "treatment technology selection (NF vs. BWRO vs. EDR), TWDB 2026 State Water Plan "
            "brackish strategies by region (especially Regions A, B, L, M), TCEQ permitting "
            "for new brackish wells, market size estimate (MGD capacity in development/planned), "
            "and key project examples. Reference TWDB Brackish Groundwater Assessment, AWWA "
            "brackish water treatment market report, and competitive landscape (EPC firms, "
            "technology vendors)."
        ),
    },
    {
        "slug": "market_intel_water_reuse_regulations",
        "title": "Market Intelligence: Water Reuse Regulatory Landscape — Texas and National",
        "domain": "water",
        "document_type": "market_intelligence",
        "prompt": (
            "Write a 700–950 word market intelligence document on the water reuse regulatory "
            "landscape in Texas and nationally. Cover: TCEQ Chapter 210 reclaimed water "
            "regulations (indirect potable reuse, industrial, irrigation), Texas DPR rule "
            "development status (TCEQ vs. national EPA guidance), EPA 2012 Guidelines for "
            "Water Reuse update status, comparison of Texas regulations to California Title 22 "
            "and Florida Chapter 62-610, market drivers (drought, supply constraints, TWDB "
            "2026 Plan reuse targets), and major Texas reuse projects. Reference EPA water "
            "reuse action plan, AWWA potable reuse framework, and TWDB reuse project database."
        ),
    },
    {
        "slug": "market_intel_twdb_funding_programs",
        "title": "Market Intelligence: TWDB Funding Programs — SWIFT, CWSRF, DWSRF, and EDAP",
        "domain": "water",
        "document_type": "market_intelligence",
        "prompt": (
            "Write an 800–1100 word market intelligence document on TWDB financial assistance "
            "programs. Cover in detail: SWIFT (State Water Implementation Fund for Texas) — "
            "eligible projects, loan terms (interest rate, amortization up to 30 years, "
            "subordinate lien structures), application process and scoring criteria, $6.6B fund "
            "capitalization; CWSRF (Clean Water State Revolving Fund) — wastewater and stormwater "
            "eligibility, green project reserve; DWSRF (Drinking Water SRF) — drinking water "
            "system eligibility, disadvantaged community subsidies; EDAP (Economically Distressed "
            "Areas Program) — eligibility criteria for colonias and low-income rural areas, grant "
            "vs. loan components. Reference TWDB Financial Assistance Programs rules (31 TAC), "
            "TWDB 2024 annual report, and EPA CWSRF/DWSRF federal guidelines."
        ),
    },
    {
        "slug": "market_intel_drought_contingency_planning",
        "title": "Market Intelligence: Drought Contingency Planning for Texas Water Utilities",
        "domain": "water",
        "document_type": "market_intelligence",
        "prompt": (
            "Write a 700–900 word market intelligence document on drought contingency planning "
            "for Texas water utilities. Cover: TCEQ Chapter 288 mandatory drought contingency "
            "plan elements (trigger levels, water use restrictions, enforcement), lessons from "
            "the 2011 drought (record statewide drought — 14 public water systems ran out of "
            "water), TWDB Water IQ public education programs, tiered water pricing effectiveness, "
            "emergency interconnect agreements, alternative supply activation lead times, and "
            "TCEQ enforcement of conservation plans. Reference TWDB drought planning guidance, "
            "TCEQ 30 TAC Chapter 288, and AWWA drought management best practices."
        ),
    },
    {
        "slug": "market_intel_water_conservation_roi",
        "title": "Market Intelligence: Water Conservation Program ROI — Texas Case Studies",
        "domain": "water",
        "document_type": "market_intelligence",
        "prompt": (
            "Write a 700–950 word market intelligence document on return on investment for "
            "municipal water conservation programs in Texas. Cover: demand reduction per dollar "
            "invested by BMP type (landscape irrigation efficiency, residential indoor audits, "
            "industrial process improvements, distribution system loss control), avoided supply "
            "development cost comparison (conservation vs. new supply at $/acre-foot), TWDB "
            "conservation loan and grant programs, SAWS San Antonio conservation program as "
            "benchmark (50+ gpcd reduction over 20 years), and Texas Water Conservation "
            "Advisory Council BMP effectiveness data. Reference TWDB BMP cost-effectiveness "
            "studies and AWWA M52 Water Conservation Programs guidance."
        ),
    },
    {
        "slug": "market_intel_texas_water_rights",
        "title": "Market Intelligence: Texas Water Rights — Procurement and Development Strategy",
        "domain": "water",
        "document_type": "market_intelligence",
        "prompt": (
            "Write a 700–1000 word market intelligence document on Texas water rights law for "
            "infrastructure developers. Cover: prior appropriation doctrine (first in time, first "
            "in right), surface water rights under Texas Water Code Chapter 11, groundwater "
            "ownership (rule of capture, GCD regulation), TCEQ water right permitting process "
            "(applications, hearings, environmental flow standards), water right transfer "
            "mechanisms (sales, leases, temporary permits), Gulf Coast Aquifer groundwater "
            "markets, and inter-basin transfer requirements. Reference Texas Water Code, TCEQ "
            "Water Rights Permitting procedures, Texas Supreme Court Edwards Aquifer Authority "
            "v. Day ruling, and TWDB 2026 State Water Plan water rights context."
        ),
    },
    {
        "slug": "market_intel_municipal_water_asset_management",
        "title": "Market Intelligence: Municipal Water Asset Management — Texas Market",
        "domain": "water",
        "document_type": "market_intelligence",
        "prompt": (
            "Write a 700–900 word market intelligence document on the Texas municipal water "
            "asset management market. Cover: AWIA 2018 risk and resilience assessment "
            "requirements for utilities serving >3,300 people, TWDB SWIFT asset management "
            "prerequisite review, market size estimate (number of CWSs in Texas >500 connections "
            "without current AMP), technology platforms (GIS, CMMS, hydraulic modeling "
            "integration), and how AM programs connect to TCEQ Chapter 290 capacity development "
            "criteria. Reference EPA asset management assistance programs, AWWA AM09 framework, "
            "and TWDB asset management funding eligibility. Identify key market segments: large "
            "municipal utilities, small to medium CWSs, water supply corporations."
        ),
    },
    {
        "slug": "market_intel_rural_water_compliance",
        "title": "Market Intelligence: Rural Water System Compliance Challenges in Texas",
        "domain": "water",
        "document_type": "market_intelligence",
        "prompt": (
            "Write a 700–950 word market intelligence document on compliance challenges facing "
            "rural water systems in Texas. Cover: profile of Texas Water Supply Corporations "
            "and rural SUD systems (number, typical size, geographic concentration), common "
            "violation types (TCR, pressure, monitoring), TCEQ capacity development strategy "
            "requirements, operator certification shortages in rural Texas, infrastructure age "
            "and capital needs, TWDB EDAP and rural programs funding availability, and "
            "consolidation/regionalization as a compliance solution. Reference TCEQ Texas "
            "Drinking Water Watch database, TWDB rural programs, USDA RD Water and Environmental "
            "Program, and EPA rural water technical assistance (RCAP/NRWA) programs."
        ),
    },

    # =========================================================================
    # FUNDING AND GRANTS GUIDES (6)
    # =========================================================================
    {
        "slug": "funding_guide_twdb_swift",
        "title": "Funding Guide: TWDB SWIFT Loan Program — Application and Positioning",
        "domain": "water",
        "document_type": "funding_grants_guide",
        "prompt": (
            "Write an 800–1100 word funding guide for the TWDB State Water Implementation Fund "
            "for Texas (SWIFT) loan program. Cover: program purpose and $6.6B fund capitalization, "
            "eligible project types (water supply, treatment, transmission, reuse, conservation), "
            "SWIFT vs. TWDB CWSRF/DWSRF positioning, loan terms (interest rate of 50% of market "
            "rate for political subdivisions, up to 30-year amortization, subordinate lien option), "
            "application cycle (quarterly intake windows), required documentation (engineering "
            "feasibility report, financial assessment, asset management plan), scoring criteria "
            "alignment with TWDB 2026 State Water Plan strategies, and how to position a project "
            "for maximum scoring. Reference 31 TAC Chapter 363 (SWIFT rules), TWDB Financial "
            "Assistance Program Guide, and TWDB 2026 State Water Plan priority project types."
        ),
    },
    {
        "slug": "funding_guide_epa_cwsrf_dwsrf",
        "title": "Funding Guide: EPA CWSRF and DWSRF — Clean and Drinking Water State Revolving Funds",
        "domain": "water",
        "document_type": "funding_grants_guide",
        "prompt": (
            "Write a 750–1000 word funding guide for the EPA Clean Water State Revolving Fund "
            "(CWSRF) and Drinking Water State Revolving Fund (DWSRF) as administered by TWDB "
            "in Texas. Cover: eligible project categories (CWSRF: wastewater, stormwater, NPS "
            "pollution; DWSRF: drinking water system improvements), disadvantaged community "
            "subsidized loan and principal forgiveness provisions, Green Project Reserve (GPR) "
            "set-aside (20% for green infrastructure, water/energy efficiency, climate resilience), "
            "application process and priority system, IIJA supplemental SRF capitalizations "
            "(additional $11.7B CWSRF + $15B DWSRF nationally), and how TWDB coordinates "
            "SWIFT + SRF in a funding stack. Reference 40 CFR Part 35, TWDB Financial Assistance "
            "Program Rules, and EPA SRF annual report data."
        ),
    },
    {
        "slug": "funding_guide_fema_bric",
        "title": "Funding Guide: FEMA BRIC — Building Resilient Infrastructure and Communities",
        "domain": "environmental",
        "document_type": "funding_grants_guide",
        "prompt": (
            "Write a 750–1000 word funding guide for the FEMA Building Resilient Infrastructure "
            "and Communities (BRIC) grant program. Cover: program purpose and annual funding "
            "levels ($1B/year under IIJA), eligible activities (hazard mitigation projects, "
            "capability and capacity building, management costs), benefit-cost analysis (BCA) "
            "requirements and FEMA BCA Toolkit, NEPA environmental review, application "
            "preparation timeline (NOFO → state application → FEMA review → award), Texas "
            "Division of Emergency Management (TDEM) role as pass-through grantee, 25% non-"
            "federal match requirement and waiver conditions, eligible infrastructure sectors "
            "(transportation, water, energy), and competitive scoring criteria. Reference FEMA "
            "BRIC NOFO, FEMA HMA Unified Guidance, and TDEM grant programs."
        ),
    },
    {
        "slug": "funding_guide_iija_water_provisions",
        "title": "Funding Guide: IIJA Water Infrastructure Provisions — Bipartisan Infrastructure Law",
        "domain": "water",
        "document_type": "funding_grants_guide",
        "prompt": (
            "Write an 800–1100 word funding guide to the water infrastructure provisions of "
            "the Infrastructure Investment and Jobs Act (IIJA / Bipartisan Infrastructure Law, "
            "2021). Cover: the $55B water infrastructure investment summary, key programs by "
            "category — DWSRF supplemental capitalization ($15B), CWSRF supplemental ($11.7B), "
            "lead service line replacement ($15B via DWSRF), emerging contaminants (PFAS, $10B), "
            "small and disadvantaged community grants ($1.87B), rural and small water grants "
            "($360M), water recycling and reuse ($1B), desalination ($250M), water storage and "
            "conveyance ($1.1B), drought ($1.1B), and aquifer recharge ($250M). Explain Texas "
            "allocation formula, TWDB administration, and sequencing strategy for stacking IIJA "
            "funds with SWIFT. Reference EPA IIJA guidance, TWDB IIJA implementation plan, and "
            "30 TAC TWDB financial assistance rules."
        ),
    },
    {
        "slug": "funding_guide_srf_application_template",
        "title": "Funding Guide: State Revolving Fund Application — Preparation Template",
        "domain": "water",
        "document_type": "funding_grants_guide",
        "prompt": (
            "Write a 750–1000 word application preparation guide and template framework for "
            "a Texas CWSRF or DWSRF loan application through TWDB. Include sections: "
            "project description (what, why, where, who, cost, schedule), engineering "
            "feasibility report requirements (TCEQ Chapter 290 design criteria compliance, "
            "alternatives analysis, preliminary cost estimate, design basis), financial "
            "assessment documentation (existing debt, rate structure, user rate affordability "
            "per EPA guidance), environmental review (NEPA categorical exclusion checklist, "
            "floodplain review, historic properties), asset management plan requirements "
            "(AWIA 2018 for DWSRF, TWDB AM criteria), and priority system scoring factors. "
            "Include a document checklist and common application deficiency list based on "
            "TWDB review experience."
        ),
    },
    {
        "slug": "funding_guide_iija_transportation",
        "title": "Funding Guide: IIJA Transportation Infrastructure Programs — Texas Focus",
        "domain": "transportation",
        "document_type": "funding_grants_guide",
        "prompt": (
            "Write an 800–1100 word funding guide to the transportation infrastructure provisions "
            "of IIJA relevant to Texas. Cover: Bridge Formula Program ($26.5B nationally — "
            "Texas allocation ~$1.5B over 5 years), RAISE discretionary grants, MEGA grants "
            "($1B+ projects), INFRA grants, Safe Streets program, Carbon Reduction program, "
            "Congestion Relief program for urban areas, and the Reconnecting Communities pilot. "
            "Explain TxDOT's Unified Transportation Program (UTP) and how IIJA formula funds "
            "flow through TxDOT to counties and MPOs. Include application timeline, eligibility "
            "rules for counties and municipalities, match requirements, and Davis-Bacon labor "
            "standards compliance. Reference FHWA IIJA program guidance and TxDOT UTP 2025."
        ),
    },
]


# Verify total
assert len(DOCUMENT_SPECS) == 80, f"Expected 80 documents, got {len(DOCUMENT_SPECS)}"


# ---------------------------------------------------------------------------
# Core helpers
# ---------------------------------------------------------------------------

def _get_clients():
    """Instantiate Azure OpenAI and Azure AI Search clients from environment."""
    openai_endpoint = os.environ["AZURE_OPENAI_ENDPOINT"]
    openai_api_key = os.environ["AZURE_OPENAI_API_KEY"]
    search_endpoint = os.environ["AZURE_SEARCH_ENDPOINT"]
    search_api_key = os.environ["AZURE_SEARCH_API_KEY"]
    index_name = os.environ["AZURE_SEARCH_INDEX_NAME"]

    oai_client = AzureOpenAI(
        azure_endpoint=openai_endpoint,
        api_key=openai_api_key,
        api_version="2024-02-01",
    )

    search_client = SearchClient(
        endpoint=search_endpoint,
        index_name=index_name,
        credential=AzureKeyCredential(search_api_key),
    )

    return oai_client, search_client


def _count_existing_synthetic_docs(search_client: SearchClient) -> int:
    """Return count of documents in the index with source='synthetic'."""
    results = search_client.search(
        search_text="*",
        filter="source eq 'synthetic'",
        select=["id"],
        include_total_count=True,
        top=0,
    )
    count = results.get_count()
    return count if count is not None else 0


def _generate_document(oai_client: AzureOpenAI, spec: dict) -> str:
    """Call GPT-4o with a structured prompt and return the generated document text."""
    system_message = (
        "You are a senior infrastructure engineering consultant at a global firm. "
        "Write professional, domain-realistic technical documents. Reference real standards, "
        "programs, and regulatory frameworks accurately. Documents should be suitable for "
        "internal firm knowledge base use by consultants and solutions architects. "
        "Do not add any preamble or meta-commentary — write the document directly."
    )

    user_message = (
        f"Document title: {spec['title']}\n"
        f"Document type: {spec['document_type']}\n"
        f"Domain: {spec['domain']}\n\n"
        f"Instructions: {spec['prompt']}"
    )

    response = oai_client.chat.completions.create(
        model=COMPLETION_MODEL,
        messages=[
            {"role": "system", "content": system_message},
            {"role": "user", "content": user_message},
        ],
        temperature=0.7,
        max_tokens=3000,
    )

    return response.choices[0].message.content.strip()


def _chunk_text(text: str, encoding: tiktoken.Encoding) -> list[str]:
    """Chunk text at CHUNK_SIZE_TOKENS with CHUNK_OVERLAP_TOKENS overlap."""
    tokens = encoding.encode(text)
    chunks = []
    start = 0
    while start < len(tokens):
        end = min(start + CHUNK_SIZE_TOKENS, len(tokens))
        chunks.append(encoding.decode(tokens[start:end]))
        if end == len(tokens):
            break
        start += CHUNK_SIZE_TOKENS - CHUNK_OVERLAP_TOKENS
    return chunks


def _embed(oai_client: AzureOpenAI, text: str) -> list[float]:
    """Embed text using Azure OpenAI text-embedding-ada-002."""
    response = oai_client.embeddings.create(
        model=EMBEDDING_MODEL,
        input=text,
    )
    return response.data[0].embedding


def _slugify(text: str) -> str:
    """Convert text to a URL-safe slug."""
    return re.sub(r"[^a-zA-Z0-9_-]", "_", text.lower())[:80]


def _upsert_chunks(
    search_client: SearchClient,
    oai_client: AzureOpenAI,
    spec: dict,
    doc_text: str,
    encoding: tiktoken.Encoding,
    now_iso: str,
) -> int:
    """Chunk, embed, and upsert a document's chunks into Azure AI Search."""
    chunks = _chunk_text(doc_text, encoding)
    doc_slug = spec["slug"]
    docs_to_upsert = []

    for chunk_idx, chunk_text in enumerate(chunks):
        chunk_id = f"synthetic_{doc_slug}_{chunk_idx}"
        vector = _embed(oai_client, chunk_text)

        docs_to_upsert.append({
            "id": chunk_id,
            "content": chunk_text,
            "content_vector": vector,
            "source": SYNTHETIC_SOURCE,
            "document_type": spec["document_type"],
            "domain": spec["domain"],
            "last_updated": now_iso,
            "chunk_index": chunk_idx,
            "source_url": f"synthetic://{doc_slug}",
        })

    if docs_to_upsert:
        search_client.upsert_documents(documents=docs_to_upsert)

    return len(chunks)


# ---------------------------------------------------------------------------
# Main entry point
# ---------------------------------------------------------------------------

def main():
    """
    Generate and index all 80 synthetic documents.

    Idempotent: checks Azure AI Search for existing synthetic docs first.
    If count >= MIN_SYNTHETIC_DOCS (80), exits immediately.
    """
    log.info("Starting synthetic document generation — checking existing index count...")

    oai_client, search_client = _get_clients()

    existing_count = _count_existing_synthetic_docs(search_client)
    log.info("Found %d existing synthetic documents in Azure AI Search.", existing_count)

    if existing_count >= MIN_SYNTHETIC_DOCS:
        log.info(
            "Index already has %d synthetic documents (>= %d required). "
            "Skipping generation.",
            existing_count,
            MIN_SYNTHETIC_DOCS,
        )
        return

    log.info(
        "Generating %d synthetic documents (%d already indexed)...",
        MIN_SYNTHETIC_DOCS - existing_count,
        existing_count,
    )

    enc = tiktoken.get_encoding("cl100k_base")
    now_iso = datetime.now(timezone.utc).isoformat()

    total_chunks = 0
    generated_count = 0

    for i, spec in enumerate(DOCUMENT_SPECS):
        slug = spec["slug"]
        log.info("[%d/%d] Generating: %s", i + 1, len(DOCUMENT_SPECS), spec["title"])

        try:
            doc_text = _generate_document(oai_client, spec)
            word_count = len(doc_text.split())
            log.info("  Generated %d words for '%s'", word_count, slug)

            chunk_count = _upsert_chunks(
                search_client, oai_client, spec, doc_text, enc, now_iso
            )
            log.info("  Indexed %d chunks for '%s'", chunk_count, slug)
            total_chunks += chunk_count
            generated_count += 1

        except Exception as exc:
            log.error("  ERROR generating '%s': %s", slug, exc, exc_info=True)
            # Continue with remaining documents — do not abort the full run
            continue

    log.info(
        "Synthetic document generation complete. "
        "Generated: %d/%d documents. Total chunks indexed: %d.",
        generated_count,
        len(DOCUMENT_SPECS),
        total_chunks,
    )


if __name__ == "__main__":
    main()
