---
apiVersion: v1
kind: Namespace
metadata:
  name: infra-advisor
  labels:
    app.kubernetes.io/part-of: infra-advisor-ai
---
apiVersion: v1
kind: Namespace
metadata:
  name: kafka
  labels:
    app.kubernetes.io/part-of: infra-advisor-ai
---
apiVersion: v1
kind: Namespace
metadata:
  name: airflow
  labels:
    app.kubernetes.io/part-of: infra-advisor-ai
---
apiVersion: v1
kind: Namespace
metadata:
  name: datadog
  labels:
    app.kubernetes.io/part-of: infra-advisor-ai
