apiVersion: v1
kind: Service
metadata:
  name: datadog-agent
  namespace: datadog
  labels:
    app: datadog-agent
spec:
  type: ClusterIP
  selector:
    app: datadog-agent
  ports:
    - name: apm
      port: 8126
      targetPort: 8126
      protocol: TCP
    - name: dogstatsd
      port: 8125
      targetPort: 8125
      protocol: UDP
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
      protocol: TCP
    - name: otlp-http
      port: 4318
      targetPort: 4318
      protocol: TCP
