kind: "DatadogAgent"
apiVersion: "datadoghq.com/v2alpha1"
metadata:
  name: "datadog"
  namespace: "datadog"
  annotations:
    agent.datadoghq.com/appsec.injector.enabled: "true"
spec:
  global:
    clusterName: "aks-infra-advisor-dev"
    site: "us3.datadoghq.com"
    credentials:
      apiSecret:
        secretName: "datadog-secret"
        keyName: "api-key"
    tags:
      - "env:dev"
  features:
    clusterChecks:
      enabled: true
    orchestratorExplorer:
      enabled: true
    otelCollector:
      enabled: true
      ports:
        - containerPort: 4317
          hostPort: 4317
          name: otel-grpc
        - containerPort: 4318
          hostPort: 4318
          name: otel-http
      conf:
        configData: |-
          receivers:
            prometheus:
              config:
                scrape_configs:
                  - job_name: "datadog-agent"
                    scrape_interval: 10s
                    static_configs:
                      - targets:
                          - 0.0.0.0:8888
            otlp:
              protocols:
                grpc:
                  endpoint: 0.0.0.0:4317
                http:
                  endpoint: 0.0.0.0:4318
          exporters:
            debug:
              verbosity: normal
            datadog:
              api:
                key: ${env:DD_API_KEY}
                site: ${env:DD_SITE}
              sending_queue:
                batch:
                  flush_timeout: 10s
          processors:
            infraattributes:
              cardinality: 2
          connectors:
            datadog/connector:
              traces:
          service:
            pipelines:
              traces:
                receivers: [otlp]
                processors: [infraattributes]
                exporters: [datadog, datadog/connector]
              metrics:
                receivers: [otlp, datadog/connector, prometheus]
                processors: [infraattributes]
                exporters: [datadog]
              logs:
                receivers: [otlp]
                processors: [infraattributes]
                exporters: [datadog]
    apm:
      instrumentation:
        enabled: true
        targets:
          - name: "infra-advisor-target"
            namespaceSelector:
              matchLabels:
                kubernetes.io/metadata.name: infra-advisor
            ddTraceVersions:
              python: "4"
              js: "5"
            ddTraceConfigs:
              - name: "DD_PROFILING_ENABLED"
                value: "auto"
              - name: "DD_DATA_STREAMS_ENABLED"
                value: "true"
    logCollection:
      enabled: true
      containerCollectAll: true
    asm:
      threats:
        enabled: true
      sca:
        enabled: true
      iast:
        enabled: true
    cws:
      enabled: true
    cspm:
      enabled: true
    sbom:
      enabled: true
      containerImage:
        enabled: true
      host:
        enabled: true
    usm:
      enabled: true
    npm:
      enabled: true
    liveProcessCollection:
      enabled: true
    processDiscovery:
      enabled: true
  override:
    nodeAgent:
      env:
        - name: DD_POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dd-postgres-secret
              key: DD_POSTGRES_PASSWORD
    clusterAgent:
      containers:
        cluster-agent:
          env:
            - name: "DD_ADMISSION_CONTROLLER_ADD_AKS_SELECTORS"
              value: "true"
