apiVersion: v1
kind: ConfigMap
metadata:
  name: load-generator-config
  namespace: infra-advisor
  labels:
    app: load-generator
data:
  DD_ENV: "dev"
  DD_SERVICE: "infra-advisor-load-generator"
  DD_VERSION: "latest"
  DD_AGENT_HOST: "datadog-agent.datadog.svc.cluster.local"
  DD_TRACE_AGENT_PORT: "8126"
  DD_DOGSTATSD_PORT: "8125"
  DD_CODE_ORIGIN_FOR_SPANS_ENABLED: "true"
  DD_DATA_STREAMS_ENABLED: "true"
  KAFKA_BOOTSTRAP_SERVERS: "kafka-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092"
  AGENT_API_URL: "http://agent-api.infra-advisor.svc.cluster.local:8001"
  LOG_LEVEL: "INFO"
